# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    cd ./web
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: react'
  inputs:
    PathtoPublish: 'web/build'
